name: xai
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=4
  - absl-py=2.3.1
  - affine=2.4.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - anyio=4.10.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.5
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.7.3
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.19.1
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - captum=0.7.0
  - cartopy=0.25.0
  - cdsapi=0.7.6
  - certifi=2025.8.3
  - cffi=1.17.1
  - cftime=1.6.4
  - charls=2.4.2
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - configobj=5.0.9
  - contourpy=1.3.3
  - cpython=3.12.11
  - crc32c=2.7.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.0.1
  - dash=2.18.2
  - dash_cytoscape=0.2.0
  - dask=2025.7.0
  - dask-core=2025.7.0
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - dill=0.4.0
  - distributed=2025.7.0
  - donfig=0.8.1.post1
  - double-conversion=3.3.1
  - ecmwf-datastores-client=0.4.0
  - emcee=3.1.6
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - ffmpeg=7.1.1
  - filelock=3.18.0
  - flask=3.1.1
  - flatbuffers=24.12.23
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.13.3
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - gast=0.6.0
  - gdk-pixbuf=2.42.12
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.13.1
  - geotiff=1.7.4
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gevent=25.5.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - greenlet=3.2.4
  - grpcio=1.67.1
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=11.3.3
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2025.8.2
  - imageio=2.37.0
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - intake=2.0.8
  - interpret=0.7.0
  - interpret-core=0.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json-c=0.18
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.0
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jxrlib=1.1
  - keras=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lark=1.2.2
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - level-zero=1.24.1
  - libabseil=20240722.0
  - libaec=1.1.4
  - libarchive=3.8.1
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libboost=1.88.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libde265=1.0.15
  - libdeflate=1.24
  - libdrm=2.4.125
  - libebm=0.7.0
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgdal-core=3.10.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.3
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.55
  - libgrpc=1.67.1
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libhwy=1.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblightgbm=4.6.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libml_dtypes-headers=0.5.2
  - libmpdec=4.0.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopencv=4.11.0
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libparquet=19.0.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libtensorflow_cc=2.18.0
  - libtensorflow_framework=2.18.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libudev1=257.7
  - libunistring=0.9.10
  - libunwind=1.8.2
  - liburing=2.11
  - libusb=1.0.29
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.0.3
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lightgbm=4.6.0
  - lime=0.2.0.1
  - llvm-openmp=20.1.8
  - llvmlite=0.44.0
  - locket=1.0.0
  - lz4=4.4.4
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markdown=3.8.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minizip=4.0.10
  - mistune=3.1.3
  - mkl=2024.2.2
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - multiprocess=0.70.18
  - multiurl=0.3.7
  - munkres=1.1.4
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - namex=0.1.0
  - narwhals=2.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.5
  - nlohmann_json=3.12.0
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numcodecs=0.16.1
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - opencv=4.11.0
  - openexr=3.3.5
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.2
  - opt_einsum=3.4.0
  - optree=0.17.0
  - orc=2.1.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.1
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.4
  - partd=1.4.2
  - pathos=0.3.4
  - patsy=1.0.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - plotly=6.2.0
  - pooch=1.8.2
  - pox=0.3.6
  - ppft=1.7.7
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - protobuf=5.28.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-opencv=4.11.0
  - py-xgboost=3.0.3
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pybind11=3.0.0
  - pybind11-global=3.0.0
  - pycparser=2.22
  - pyextremes=2.3.3
  - pygments=2.19.2
  - pykdtree=1.4.3
  - pyogrio=0.11.0
  - pyorbital=1.10.2
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pyresample=1.34.2
  - pyshp=3.0.0
  - pyside6=6.8.3
  - pysocks=1.7.1
  - pyspectral=0.13.6
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=25.2.10
  - python-geotiepoints=1.7.5
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch=2.6.0
  - pytz=2025.2
  - pywavelets=1.9.0
  - pyyaml=6.0.2
  - pyzmq=27.0.1
  - qhull=2020.2
  - qt6-main=6.8.3
  - rasterio=1.4.3
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - retrying=1.4.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - rioxarray=0.19.0
  - rpds-py=0.27.0
  - s2n=1.5.14
  - salib=1.5.1
  - satpy=0.57.0
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - sdl2=2.32.54
  - sdl3=3.2.20
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shap=0.48.0
  - shapely=2.1.1
  - six=1.17.0
  - sleef=3.8
  - slicer=0.0.8
  - snappy=1.2.2
  - sniffio=1.3.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.7
  - sqlite=3.50.4
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.0.2
  - sympy=1.14.0
  - tbb=2021.13.0
  - tblib=3.1.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2025.6.11
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - torchvision=0.21.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - trollimage=1.26.0
  - trollsift=0.5.3
  - types-python-dateutil=2.9.0.20250708
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - ultraplot=1.60.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wget=1.21.4
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - wrapt=1.17.2
  - x264=1!164.3095
  - x265=3.5
  - xarray=2025.7.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xgboost=3.0.3
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - yarl=1.20.1
  - zarr=3.1.1
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zope.event=5.1.1
  - zope.interface=7.2
  - zstandard=0.23.0
  - zstd=1.5.7
